export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_USER : "SET_USER",
    SELECT_PLAYLIST :"SELECT_PLAYLIST",
    SET_SELECTION_PLAYLIST_ID: "SET_SELECTION_PLAYLIST_ID",
}
